# Generated by Django 2.2 on 2020-08-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='harga',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='menu',
            field=models.TextField(default=''),
        ),
    ]
