# Generated by Django 2.2 on 2020-09-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
